prompt='Enter dial key ';

m=input(prompt,'s'); states=['1','2','3','A','4','5','6','B','7','8','9','C','*','0','#','D'];

y=ismember(m,states); if (y==0)
disp("Wrong input");
return end

if(m=='1') 
	fc1=697; fc2=1209;
end 

if(m=='2')
fc1=697;
fc2=1336; end
if(m=='3') fc1=697; fc2=1477;
end if(m=='A')
fc1=697;
fc2=1633; end
if(m=='4') fc1=770; fc2=1209;
end if(m=='5')
fc1=770;
fc2=1336; end
if(m=='6') fc1=770; fc2=1477;
end

 if(m=='B') fc1=770; fc2=1633;
end
if(m=='7') fc1=852; fc2=1209;
end if(m=='8')
fc1=852;
fc2=1336; end
if(m=='9') fc1=852; fc2=1477;
end if(m=='C')
fc1=852;
fc2=1633; end
if(m=='*') fc1=941; fc2=1209;
end if(m=='0')
fc1=941;
fc2=1336; end
if(m=='#') fc1=941; fc2=1477;
end if(m=='D')
fc1=941;
fc2=1633; end
decoder=['1','2','3','A';'4','5','6','B';'7','8','9','C';'*','0','#','D']; Fs=10000; % sampling frequency
t = 0:1/Fs:0.1; %sampling between 0 to 0.1 second at interval of 1/Fs % Sinusoidal signal is generated by using in built function cos or sin s1 = 10*cos(2*pi*fc1*t)+10*cos(2*pi*fc2*t);


noise = 10.*randn(length(s1),1);
n = 512;
y = fft(s1,n);
Y = fftshift(y);
fshift = (-n/2:n/2-1)*(Fs/n); % zero-centered frequency range powershift = abs(Y).^1/n;
% zero-centered power
figure;
plot(fshift,powershift);
% plot of discrete samples
xlabel("Frequency");ylabel("Magnitude");% defining axis else in default mode grid on;
n1=0:1:40000;
k=1/150;
t1 = 0:1/(1*Fs):0.1;
Bbp1 = k*cos(2*pi*697*t1); Bbp2 = k*cos(2*pi*770*t1); Bbp3 = k*cos(2*pi*852*t1); Bbp4 = k*cos(2*pi*941*t1); Bbp5 = k*cos(2*pi*1209*t1); Bbp6 = k*cos(2*pi*1336*t1); Bbp7 = k*cos(2*pi*1477*t1); Bbp8 = k*cos(2*pi*1633*t1);
fcutlow=687; %low cut frequency in kHz fcuthigh=707; %high cut frequency in kHz
filtsig1=filter(Bbp1,1,s1); y = fft(filtsig1,n);
Y = fftshift(y); m1=max(Y);
fshift = (-n/2:n/2-1)*(Fs/n); % zero-centered frequency range powershift = abs(Y).^1/n;
% zero-centered power
figure;
subplot(221);
plot(fshift,powershift); xlabel("Frequency");ylabel("Magnitude");

 grid on;
title("Bandpass at f=697 Hz");
fcutlow=760; %low cut frequency in kHz fcuthigh=780; %high cut frequency in kHz
filtsig2=filter(Bbp2,1,s1); y = fft(filtsig2,n);
Y = fftshift(y); m2=max(Y);
fshift = (-n/2:n/2-1)*(Fs/n); % zero-centered frequency range powershift = abs(Y).^1/n;
% zero-centered power
%figure;
subplot(222);
plot(fshift,powershift); xlabel("Frequency");ylabel("Magnitude"); grid on;
title("Bandpass at f=770 Hz");
fcutlow=842; %low cut frequency in kHz fcuthigh=862; %high cut frequency in kHz
filtsig3=filter(Bbp3,1,s1); y = fft(filtsig3,n);
Y = fftshift(y); m3=max(Y);
fshift = (-n/2:n/2-1)*(Fs/n); % zero-centered frequency range powershift = abs(Y).^1/n;
% zero-centered power
%figure;
subplot(223);
plot(fshift,powershift); xlabel("Frequency");ylabel("Magnitude"); grid on;
title("Bandpass at f= 852 Hz");
fcutlow=931; %low cut frequency in kHz

 fcuthigh=951; %high cut frequency in kHz
filtsig4=filter(Bbp4,1,s1); y = fft(filtsig4,n);
Y = fftshift(y); m4=max(Y);
fshift = (-n/2:n/2-1)*(Fs/n); % zero-centered frequency range powershift = abs(Y).^1/n;
% zero-centered power
%figure;
subplot(224);
plot(fshift,powershift); xlabel("Frequency");ylabel("Magnitude"); grid on;
title("Bandpass at f=941 Hz");
fcutlow=1199; %low cut frequency in kHz fcuthigh=1219; %high cut frequency in kHz
filtsig5=filter(Bbp5,1,s1); y = fft(filtsig5,n);
Y = fftshift(y); m5=max(Y);
fshift = (-n/2:n/2-1)*(Fs/n); % zero-centered frequency range powershift = abs(Y).^1/n;
% zero-centered power
figure;
subplot(221);
plot(fshift,powershift); xlabel("Frequency");ylabel("Magnitude"); grid on;
title("Bandpass at f=1209 Hz");
fcutlow=1326; %low cut frequency in kHz fcuthigh=1346; %high cut frequency in kHz
filtsig6=filter(Bbp6,1,s1); y = fft(filtsig6,n);
Y = fftshift(y); m6=max(Y);

 fshift = (-n/2:n/2-1)*(Fs/n); % zero-centered frequency range powershift = abs(Y).^1/n;
% zero-centered power
%figure;
subplot(222);
plot(fshift,powershift); xlabel("Frequency");ylabel("Magnitude"); grid on;
title("Bandpass at f=1336 Hz");
fcutlow=1467; %low cut frequency in kHz fcuthigh=1487; %high cut frequency in kHz
filtsig7=filter(Bbp7,1,s1); y = fft(filtsig7,n);
Y = fftshift(y); m7=max(Y);
fshift = (-n/2:n/2-1)*(Fs/n); % zero-centered frequency range powershift = abs(Y).^1/n;
% zero-centered power
%figure;
subplot(223);
plot(fshift,powershift); xlabel("Frequency");ylabel("Magnitude"); grid on;
title("Bandpass at f=1477 Hz");
fcutlow=1623; %low cut frequency in kHz fcuthigh=1643; %high cut frequency in kHz
filtsig8=filter(Bbp8,1,s1); y = fft(filtsig8,n);
Y = fftshift(y); m8=max(Y);
fshift = (-n/2:n/2-1)*(Fs/n); % zero-centered frequency range powershift = abs(Y).^1/n;
% zero-centered power
%figure;
subplot(224);
plot(fshift,powershift); xlabel("Frequency");ylabel("Magnitude");

grid on;
title("Bandpass at f=1633 Hz");
[v1, f1]=max([m1 m2 m3 m4]);
%print ("max value is %d and row is %d\n",v1,f1); [v2, f2]=max([m5 m6 m7 m8]);
%print ("max");
fprintf("number decoded is"); decoder(f1,f2)