function mytemps
c0 = uicontrol('Style','text','String','Keypad'); c0.Position = [160 350 60 20];
c1 = uicontrol('Style','pushbutton','String','1'); c1.Position = [20 300 60 20];
c1.Callback = @selection1;
c2 = uicontrol('Style','pushbutton','String','2'); c2.Position = [100 300 60 20];
c2.Callback = @selection2;
c3 = uicontrol('Style','pushbutton','String','3'); c3.Position = [180 300 60 20];
c3.Callback = @selection3;
c4 = uicontrol('Style','pushbutton','String','A'); c4.Position = [260 300 60 20];
c4.Callback = @selection4;
c5 = uicontrol('Style','pushbutton','String','4'); c5.Position = [20 225 60 20];
c5.Callback = @selection5;
c6 = uicontrol('Style','pushbutton','String','5'); c6.Position = [100 225 60 20];
c6.Callback = @selection6;
c7 = uicontrol('Style','pushbutton','String','6'); c7.Position = [180 225 60 20];
c7.Callback = @selection7;

 c8 = uicontrol('Style','pushbutton','String','B'); c8.Position = [260 225 60 20];
c8.Callback = @selection8;
c9 = uicontrol('Style','pushbutton','String','7'); c9.Position = [20 150 60 20];
c9.Callback = @selection9;
c10 = uicontrol('Style','pushbutton','String','8'); c10.Position = [100 150 60 20];
c10.Callback = @selection10;
c11 = uicontrol('Style','pushbutton','String','9'); c11.Position = [180 150 60 20];
c11.Callback = @selection11;
c12 = uicontrol('Style','pushbutton','String','C'); c12.Position = [260 150 60 20];
c12.Callback = @selection12;
c13 = uicontrol('Style','pushbutton','String','*'); c13.Position = [20 75 60 20];
c13.Callback = @selection13;
c14 = uicontrol('Style','pushbutton','String','0'); c14.Position = [100 75 60 20];
c14.Callback = @selection14;
c15 = uicontrol('Style','pushbutton','String','#'); c15.Position = [180 75 60 20];
c15.Callback = @selection15;
c16 = uicontrol('Style','pushbutton','String','D'); c16.Position = [260 75 60 20];

 c16.Callback = @selection16;
c17 = uicontrol('Style','text','String','Decoder'); c17.Position = [400 225 60 20];
function selection1(src,event) test1('1');
end
function selection2(src,event) test1('2');
end
function selection3(src,event) test1('3');
end
function selection4(src,event) test1('A');
end
function selection5(src,event)
test1('4');
end
function selection6(src,event)
test1('5');

 end
function selection7(src,event)
test1('6');
end
function selection8(src,event)
test1('B');
end
function selection9(src,event)
test1('7');
end
function selection10(src,event)
test1('8');
end
function selection11(src,event)
test1('9');
end
function selection12(src,event)
test1('C');
end
function selection13(src,event)
test1('*');
end

 function selection14(src,event) test1('0');
end
function selection15(src,event)
test1('#');
end
function selection16(src,event)
test1('D');
end
function test1(m) states=['1','2','3','A','4','5','6','B','7','8','9','C','*','0','#','D'];
y=ismember(m,states); if (y==0)
disp("Wrong input");
return end
if(m=='1') fc1=697; fc2=1209;
end if(m=='2')
fc1=697;
fc2=1336; end
if(m=='3') fc1=697; fc2=1477;
end if(m=='A')

 fc1=697;
fc2=1633; end
if(m=='4') fc1=770; fc2=1209;
end if(m=='5')
fc1=770;
fc2=1336; end
if(m=='6') fc1=770; fc2=1477;
end if(m=='B')
fc1=770;
fc2=1633; end
if(m=='7') fc1=852; fc2=1209;
end if(m=='8')
fc1=852;
fc2=1336; end
if(m=='9') fc1=852; fc2=1477;
end if(m=='C')
fc1=852;
fc2=1633; end
if(m=='*') fc1=941; fc2=1209;
end if(m=='0')
fc1=941; fc2=1336;

 end if(m=='#')
fc1=941;
fc2=1477; end
if(m=='D') fc1=941; fc2=1633;
end
decoder=['1','2','3','A';'4','5','6','B';'7','8','9','C';'*','0','#','D']; Fs=10000; % sampling frequency
t = 0:1/Fs:0.1; %sampling between 0 to 0.1 second at interval of 1/Fs % Sinusoidal signal is generated by using in built function cos or sin s1 = 10*cos(2*pi*fc1*t)+10*cos(2*pi*fc2*t);
noise = 10.*randn(length(s1),1);

s1=s1+noise;
n = 512;
y = fft(s1,n);
Y = fftshift(y);
fshift = (-n/2:n/2-1)*(Fs/n); % zero-centered frequency range powershift = abs(Y).^1/n;
% zero-centered power
% plot of discrete samples
n1=0:1:40000; k=1/150;
t1 = 0:1/(1*Fs):0.1;
Bbp1 = k*cos(2*pi*697*t1); Bbp2 = k*cos(2*pi*770*t1); Bbp3 = k*cos(2*pi*852*t1); Bbp4 = k*cos(2*pi*941*t1); Bbp5 = k*cos(2*pi*1209*t1); Bbp6 = k*cos(2*pi*1336*t1); Bbp7 = k*cos(2*pi*1477*t1); Bbp8 = k*cos(2*pi*1633*t1);
fcutlow=687; %low cut frequency in kHz fcuthigh=707; %high cut frequency in kHz

 filtsig1=filter(Bbp1,1,s1); y = fft(filtsig1,n);
Y = fftshift(y); m1=max(Y);
fcutlow=760; %low cut frequency in kHz fcuthigh=780; %high cut frequency in kHz
filtsig2=filter(Bbp2,1,s1); y = fft(filtsig2,n);
Y = fftshift(y); m2=max(Y);
fshift = (-n/2:n/2-1)*(Fs/n); % zero-centered frequency range powershift = abs(Y).^1/n;
% zero-centered power
%figure;
fcutlow=842; %low cut frequency in kHz fcuthigh=862; %high cut frequency in kHz
filtsig3=filter(Bbp3,1,s1); y = fft(filtsig3,n);
Y = fftshift(y); m3=max(Y);
fcutlow=931; %low cut frequency in kHz fcuthigh=951; %high cut frequency in kHz
filtsig4=filter(Bbp4,1,s1); y = fft(filtsig4,n);
Y = fftshift(y); m4=max(Y);

 fcutlow=1199; %low cut frequency in kHz fcuthigh=1219; %high cut frequency in kHz
filtsig5=filter(Bbp5,1,s1); y = fft(filtsig5,n);
Y = fftshift(y); m5=max(Y);
fcutlow=1326; %low cut frequency in kHz fcuthigh=1346; %high cut frequency in kHz
filtsig6=filter(Bbp6,1,s1); y = fft(filtsig6,n);
Y = fftshift(y); m6=max(Y);
fcutlow=1467; %low cut frequency in kHz fcuthigh=1487; %high cut frequency in kHz
filtsig7=filter(Bbp7,1,s1); y = fft(filtsig7,n);
Y = fftshift(y); m7=max(Y);
fcutlow=1623; %low cut frequency in kHz fcuthigh=1643; %high cut frequency in kHz
filtsig8=filter(Bbp8,1,s1); y = fft(filtsig8,n);
Y = fftshift(y); m8=max(Y);
[v1, f1]=max([m1 m2 m3 m4]);
%print ("max value is %d and row is %d\n",v1,f1); [v2, f2]=max([m5 m6 m7 m8]);

%print ("max");
ck = uicontrol('Style','pushbutton','String',decoder(f1,f2)); ck.Position = [400 175 60 20];
end end